import sys
import os

#Setup default environment. This environment
#if not 'CCDB_HOME' in os.environ:
#    print "CCDB_HOME environment variable is not found but should be set to compile the CCDB"
#    print "One can run 'source environment.bash' from your bash shell to automatically set environment variables"
#    exit(1)

HEADER = ''
OKBLUE = ''
OKGREEN = ''
WARNING = ''
FAIL = ''
ENDC = ''
BOLD = ''
UNDERLINE = ''


def supports_color():
    """
    Returns True if the running system's terminal supports color,
    and False otherwise.
    """
    plat = sys.platform
    supported_platform = plat != 'Pocket PC' and (plat != 'win32' or 'ANSICON' in os.environ)

    # isatty is not always implemented, #6223.
    is_a_tty = hasattr(sys.stdout, 'isatty') and sys.stdout.isatty()
    if not supported_platform or not is_a_tty:
        return False
    return True

def bool_to_colored_str(value):
    return "{OKGREEN}true{ENDC}" if value else "{FAIL}false{ENDC}"


if supports_color():
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


with_mysql = ARGUMENTS.get("with-mysql","true")=="true"
with_tests = ARGUMENTS.get("with-tests","false")=="true"
with_examples = ARGUMENTS.get("with-examples","false")=="true"
with_sqlite = ARGUMENTS.get("with-sqlite","true")=="true"


help = ("""
{HEADER}{BOLD}RCDB build scripts options:{ENDC}

{BOLD}{OKBLUE}with-mysql{ENDC}="""+bool_to_colored_str(with_mysql)+""" \tBuild with MySql support
{BOLD}{OKBLUE}with-sqlite{ENDC}="""+bool_to_colored_str(with_sqlite)+""" \tBuild with SQlite3 support

{BOLD}{OKBLUE}with-tests{ENDC}="""+bool_to_colored_str(with_tests)+""" \tBuild unit tests. Will be as ./bin/test_rcdb_cpp
{BOLD}{OKBLUE}with-examples{ENDC}="""+bool_to_colored_str(with_examples)+""" \tBuild with examples. Will be in ./bin

""").format(
HEADER = HEADER, OKBLUE = OKBLUE, OKGREEN = OKGREEN, WARNING = WARNING,
FAIL = FAIL, ENDC = ENDC, BOLD = BOLD, UNDERLINE = UNDERLINE)

print(help)

#Create 'default' environment. Other environments will be a copy of this one
default_env = Environment(
    #>> CCDB related default staff <<
    CPPPATH = ['#include', '#include/SQLite', '#src', '/usr/include'], #, '#include/SQLite'],
    ENV = os.environ,
    CXXFLAGS = '-std=c++11',
)


#Export 'default' environment for everything that wishes to use it
Export('default_env', 'with_mysql')

#Create 'working' environment
#default_env.Repository('src')

#Attach SConsctipts
SConscript('src/SConscript', 'default_env', variant_dir='tmp/RcdbLib', duplicate=0)

if with_tests:
    SConscript('tests/SConscript', 'default_env', variant_dir='tmp/Tests', duplicate=0)

if with_examples:
    SConscript('examples/SConscript', 'default_env', variant_dir='tmp/Examples', duplicate=0)



