#!/bin/bash
#
# The script saves information to Run Configuration database on end of run
# path to coda run statistics should be provided to script as first argument
#
#---------------------------------------------------------------------------



# 2. IS ENVIRONMENT SET?

export RCDB_HOME=${DAQ_HOME}/rcdb/rcdb_master
export LD_LIBRARY_PATH="$RCDB_HOME/cpp/lib":$LD_LIBRARY_PATH
export PYTHONPATH="$RCDB_HOME/python":$PYTHONPATH
export PATH="$RCDB_HOME":"$RCDB_HOME/bin":"$RCDB_HOME/cpp/bin":$PATH

# 1. Setup python
source ${DAQ_HOME}/rcdb/miniconda3/etc/profile.d/conda.sh
conda activate


#3. PYTHON SCRIPT START

if [[ $# -eq 1 ]]; then
	LOGFILE="$1"
        shift
else
	LOGFILE=$COOL_HOME/$SESSION/ddb/run-log/$SESSION/current_run.log
fi	

date 
echo LOG=$LOGFILE 
cat $LOGFILE
echo "RCDB_CONNECTION=$RCDB_CONNECTION"
echo "RCDB_HOME=$RCDB_HOME"
echo "PYTHONPATH=$PYTHONPATH"
#sleep 5
echo "------------- rcdb update python RCDB_HOME=$RCDB_HOME ---------------------"
echo "update.py params: $*"
echo `which python3`
python3 --version 
which python3
python3 $RCDB_HOME/python/update.py $LOGFILE "$@" 
#gdb -ex run --args python $RCDB_HOME/python/update.py $LOGFILE "$@" 

