name: Documentation generation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    # if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
      pages: write
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Introspect
        run: |
          echo "--- pwd"
          pwd
          echo "--- ls ./docs/"

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
