name: Python tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip         
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          ls $GITHUB_WORKSPACE
      
      - name: Test with unittest
        run: |
          cd $GITHUB_WORKSPACE/python
          python -m unittest discover -s $GITHUB_WORKSPACE/python/tests -t $GITHUB_WORKSPACE/python/tests

      - name: Test CLI commands
        run: |          
          source environment.bash
          echo "rcnd command is running"
          rcnd --help
          echo "rcdb command is running"
          rcdb --help
